# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-28 12:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gebied', models.CharField(choices=[('studie', 'studie'), ('sociaal', 'sociaal'), ('toekomst', 'toekomst'), ('studiesociaal', 'studiesociaal'), ('studietoekomst', 'studietoekomst'), ('sociaaltoekomst', 'sociaaltoekomst')], default='studie', max_length=50)),
                ('naam', models.CharField(max_length=50)),
                ('omschrijving', models.TextField()),
                ('time', models.IntegerField(default=4, verbose_name='Tijdsduur')),
                ('kosten', models.IntegerField(default=100, verbose_name='Kosten')),
                ('baten_vast', models.IntegerField(default=100, verbose_name='Vaste baten')),
                ('baten_flex', models.IntegerField(default=100, verbose_name='Flexibele baten')),
                ('experience_vast', models.IntegerField(default=100, verbose_name='Vaste exp')),
                ('experience_flex', models.IntegerField(default=100, verbose_name='Flexibele exp')),
                ('factor', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answers', models.CharField(choices=[('Ja', 'Ja'), ('Nee', 'Nee'), ('WN', 'Weet niet')], default='WN', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('sexe', models.CharField(choices=[('M', 'Man'), ('V', 'Vrouw')], default='M', max_length=1)),
                ('bank', models.IntegerField(default=150, verbose_name='Bank')),
                ('exp_tot', models.IntegerField(default=0, verbose_name='Experience totaal')),
                ('exp_stud', models.IntegerField(default=0, verbose_name='Experience studie')),
                ('exp_soc', models.IntegerField(default=0, verbose_name='Experience sociaal')),
                ('exp_toek', models.IntegerField(default=0, verbose_name='Experience toekomst')),
                ('weging_stud', models.IntegerField(default=40, verbose_name='Weging studie')),
                ('weging_soc', models.IntegerField(default=30, verbose_name='Weging sociaal')),
                ('weging_toek', models.IntegerField(default=30, verbose_name='Weging toekomst')),
                ('modules', models.ManyToManyField(to='main.Modules')),
                ('questions', models.ManyToManyField(to='main.Questions')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
