# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 06:30
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160802_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='modules',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Modules'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='questions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Questions'),
        ),
        migrations.AlterField(
            model_name='modules',
            name='cijfer',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10)], verbose_name='Cijfer'),
        ),
        migrations.AlterField(
            model_name='modules',
            name='factor',
            field=models.IntegerField(default=0, verbose_name='Factor module'),
        ),
        migrations.AlterField(
            model_name='modules',
            name='naam',
            field=models.CharField(default='NAAM', max_length=50),
        ),
        migrations.AlterField(
            model_name='modules',
            name='omschrijving',
            field=models.TextField(default='OMSCHRIJVING'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.TextField(default='QUESTION'),
        ),
    ]
