# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-28 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160728_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='gebied',
            field=models.CharField(choices=[('studie', 'studie'), ('sociaal', 'sociaal'), ('toekomst', 'toekomst'), ('studiesociaal', 'studiesociaal'), ('studietoekomst', 'studietoekomst'), ('sociaaltoekomst', 'sociaaltoekomst')], default='studie', max_length=50),
        ),
    ]
