# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-28 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20160728_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='niveau',
            field=models.IntegerField(default=1, verbose_name='Niveau'),
        ),
        migrations.AlterField(
            model_name='modules',
            name='baten_flex',
            field=models.IntegerField(default=0, verbose_name='Flexibele baten'),
        ),
        migrations.AlterField(
            model_name='modules',
            name='baten_vast',
            field=models.IntegerField(default=0, verbose_name='Vaste baten'),
        ),
        migrations.AlterField(
            model_name='modules',
            name='experience_flex',
            field=models.IntegerField(default=0, verbose_name='Flexibele exp'),
        ),
        migrations.AlterField(
            model_name='modules',
            name='experience_vast',
            field=models.IntegerField(default=0, verbose_name='Vaste exp'),
        ),
        migrations.AlterField(
            model_name='modules',
            name='kosten',
            field=models.IntegerField(default=0, verbose_name='Kosten'),
        ),
        migrations.AlterField(
            model_name='modules',
            name='tijd',
            field=models.IntegerField(default=0, verbose_name='Tijdsduur'),
        ),
    ]
