# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20160802_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='module_type',
            field=models.CharField(choices=[('Actief', 'Actief'), ('Passief', 'Passief')], default='Passief', max_length=10),
        ),
    ]
