# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-28 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20160728_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='test',
            field=models.IntegerField(default=1, verbose_name='test'),
        ),
    ]
