# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20160802_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='id_module',
            field=models.CharField(default='', max_length=15),
        ),
    ]
