# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-30 18:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_modules_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 7, 30, 18, 22, 31, 435574, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
