# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_questions_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='firstname',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='lastname',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weging_soc',
            field=models.IntegerField(blank=True, default=100, verbose_name='Weging sociaal'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weging_stud',
            field=models.IntegerField(blank=True, default=100, verbose_name='Weging studie'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weging_toek',
            field=models.IntegerField(blank=True, default=100, verbose_name='Weging toekomst'),
        ),
    ]
