# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 07:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20160801_0518'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='cijfer',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Cijfer'),
        ),
        migrations.AddField(
            model_name='modules',
            name='module_type',
            field=models.CharField(choices=[('Actief', 'Actief'), ('Pasief', 'Pasief')], default='Pasief', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='firstname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='lastname',
            field=models.CharField(max_length=50),
        ),
    ]
