# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gebied', models.CharField(choices=[('studie', 'studie'), ('sociaal', 'sociaal'), ('toekomst', 'toekomst'), ('studiesociaal', 'studiesociaal'), ('studietoekomst', 'studietoekomst'), ('sociaaltoekomst', 'sociaaltoekomst')], default='studie', max_length=50)),
                ('naam', models.CharField(default='', max_length=50)),
                ('omschrijving', models.TextField()),
                ('time', models.IntegerField(default=4, verbose_name='Tijdsduur')),
                ('kosten', models.IntegerField(default=100, verbose_name='Kosten')),
                ('baten_vast', models.IntegerField(default=100, verbose_name='Vaste baten')),
                ('baten_flex', models.IntegerField(default=100, verbose_name='Flexibele baten')),
                ('experience_vast', models.IntegerField(default=100, verbose_name='Vaste exp')),
                ('experience_flex', models.IntegerField(default=100, verbose_name='Flexibele exp')),
                ('factor', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answers', models.CharField(choices=[('Ja', 'Ja'), ('Nee', 'Nee'), ('WN', 'Weet niet')], default='WN', max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='expsociaal',
            new_name='exp_soc',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='expstudie',
            new_name='exp_stud',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='exptoekomst',
            new_name='exp_toek',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='exptotaal',
            new_name='exp_tot',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='sociaal_weging',
            new_name='weging_soc',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='studie_weging',
            new_name='weging_stud',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='toekomst_weging',
            new_name='weging_toek',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='gender',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='firstname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lastname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sexe',
            field=models.CharField(choices=[('M', 'Man'), ('V', 'Vrouw')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bank',
            field=models.IntegerField(default=150, verbose_name='Bank'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='modules',
            field=models.ManyToManyField(to='main.Modules'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='questions',
            field=models.ManyToManyField(to='main.Questions'),
        ),
    ]
