# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-28 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='modules',
            field=models.ManyToManyField(blank=True, to='main.Modules'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='questions',
            field=models.ManyToManyField(blank=True, to='main.Questions'),
        ),
    ]
