# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160728_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='weging_soc',
            field=models.IntegerField(default=30, verbose_name='Weging sociaal'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weging_stud',
            field=models.IntegerField(default=40, verbose_name='Weging studie'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weging_toek',
            field=models.IntegerField(default=30, verbose_name='Weging toekomst'),
        ),
    ]
