# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-28 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_questions_gebied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modules',
            name='time',
        ),
        migrations.AddField(
            model_name='modules',
            name='niveau',
            field=models.IntegerField(default=1, verbose_name='Niveau van course'),
        ),
        migrations.AddField(
            model_name='modules',
            name='tijd',
            field=models.IntegerField(default=4, verbose_name='Tijdsduur'),
        ),
    ]
