# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-28 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20160728_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='factor',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
