# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-02 05:53
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gebied', models.CharField(choices=[(b'studie', b'studie'), (b'sociaal', b'sociaal'), (b'toekomst', b'toekomst'), (b'studiesociaal', b'studiesociaal'), (b'studietoekomst', b'studietoekomst'), (b'sociaaltoekomst', b'sociaaltoekomst')], default=b'studie', max_length=50)),
                ('naam', models.CharField(max_length=50)),
                ('omschrijving', models.TextField()),
                ('tijd', models.IntegerField(default=0, verbose_name=b'Tijdsduur')),
                ('kosten', models.IntegerField(default=0, verbose_name=b'Kosten')),
                ('baten_vast', models.IntegerField(default=0, verbose_name=b'Vaste baten')),
                ('baten_flex', models.IntegerField(default=0, verbose_name=b'Flexibele baten')),
                ('experience_vast', models.IntegerField(default=0, verbose_name=b'Vaste exp')),
                ('experience_flex', models.IntegerField(default=0, verbose_name=b'Flexibele exp')),
                ('factor', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('niveau', models.IntegerField(default=1, verbose_name=b'Niveau van course')),
                ('module_type', models.CharField(choices=[(b'Actief', b'Actief'), (b'Pasief', b'Pasief')], default=b'Pasief', max_length=10)),
                ('cijfer', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name=b'Cijfer')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answers', models.CharField(choices=[(b'Ja', b'Ja'), (b'Nee', b'Nee'), (b'WN', b'Weet niet')], default=b'WN', max_length=50)),
                ('gebied', models.CharField(choices=[(b'studie', b'studie'), (b'sociaal', b'sociaal'), (b'toekomst', b'toekomst'), (b'studiesociaal', b'studiesociaal'), (b'studietoekomst', b'studietoekomst'), (b'sociaaltoekomst', b'sociaaltoekomst')], default=b'studie', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('sexe', models.CharField(choices=[(b'M', b'Man'), (b'V', b'Vrouw')], default=b'M', max_length=1)),
                ('bank', models.IntegerField(default=150, verbose_name=b'Bank')),
                ('exp_tot', models.IntegerField(default=0, verbose_name=b'Experience totaal')),
                ('exp_stud', models.IntegerField(default=0, verbose_name=b'Experience studie')),
                ('exp_soc', models.IntegerField(default=0, verbose_name=b'Experience sociaal')),
                ('exp_toek', models.IntegerField(default=0, verbose_name=b'Experience toekomst')),
                ('niveau', models.IntegerField(default=1, verbose_name=b'Niveau')),
                ('weging_stud', models.IntegerField(blank=True, default=100, verbose_name=b'Weging studie')),
                ('weging_soc', models.IntegerField(blank=True, default=100, verbose_name=b'Weging sociaal')),
                ('weging_toek', models.IntegerField(blank=True, default=100, verbose_name=b'Weging toekomst')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
