# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 05:54
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='baten_flex',
            field=models.IntegerField(default=0, verbose_name='Flexibele baten'),
        ),
        migrations.AlterField(
            model_name='modules',
            name='baten_vast',
            field=models.IntegerField(default=0, verbose_name='Vaste baten'),
        ),
        migrations.AlterField(
            model_name='modules',
            name='cijfer',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Cijfer'),
        ),
        migrations.AlterField(
            model_name='modules',
            name='experience_flex',
            field=models.IntegerField(default=0, verbose_name='Flexibele exp'),
        ),
        migrations.AlterField(
            model_name='modules',
            name='experience_vast',
            field=models.IntegerField(default=0, verbose_name='Vaste exp'),
        ),
        migrations.AlterField(
            model_name='modules',
            name='gebied',
            field=models.CharField(choices=[('studie', 'studie'), ('sociaal', 'sociaal'), ('toekomst', 'toekomst'), ('studiesociaal', 'studiesociaal'), ('studietoekomst', 'studietoekomst'), ('sociaaltoekomst', 'sociaaltoekomst')], default='studie', max_length=50),
        ),
        migrations.AlterField(
            model_name='modules',
            name='kosten',
            field=models.IntegerField(default=0, verbose_name='Kosten'),
        ),
        migrations.AlterField(
            model_name='modules',
            name='module_type',
            field=models.CharField(choices=[('Actief', 'Actief'), ('Pasief', 'Pasief')], default='Pasief', max_length=10),
        ),
        migrations.AlterField(
            model_name='modules',
            name='niveau',
            field=models.IntegerField(default=1, verbose_name='Niveau van course'),
        ),
        migrations.AlterField(
            model_name='modules',
            name='tijd',
            field=models.IntegerField(default=0, verbose_name='Tijdsduur'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='answers',
            field=models.CharField(choices=[('Ja', 'Ja'), ('Nee', 'Nee'), ('WN', 'Weet niet')], default='WN', max_length=50),
        ),
        migrations.AlterField(
            model_name='questions',
            name='gebied',
            field=models.CharField(choices=[('studie', 'studie'), ('sociaal', 'sociaal'), ('toekomst', 'toekomst'), ('studiesociaal', 'studiesociaal'), ('studietoekomst', 'studietoekomst'), ('sociaaltoekomst', 'sociaaltoekomst')], default='studie', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bank',
            field=models.IntegerField(default=150, verbose_name='Bank'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='exp_soc',
            field=models.IntegerField(default=0, verbose_name='Experience sociaal'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='exp_stud',
            field=models.IntegerField(default=0, verbose_name='Experience studie'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='exp_toek',
            field=models.IntegerField(default=0, verbose_name='Experience toekomst'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='exp_tot',
            field=models.IntegerField(default=0, verbose_name='Experience totaal'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='niveau',
            field=models.IntegerField(default=1, verbose_name='Niveau'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sexe',
            field=models.CharField(choices=[('M', 'Man'), ('V', 'Vrouw')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weging_soc',
            field=models.IntegerField(blank=True, default=100, verbose_name='Weging sociaal'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weging_stud',
            field=models.IntegerField(blank=True, default=100, verbose_name='Weging studie'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weging_toek',
            field=models.IntegerField(blank=True, default=100, verbose_name='Weging toekomst'),
        ),
    ]
