# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20160802_0647'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='naam_gebruiker',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='modules',
            name='status',
            field=models.CharField(choices=[('Niet gedaan', 'Niet gedaan'), ('Bezig', 'Bezig'), ('Voltooid', 'Voltooid')], default='Niet gedaan', max_length=10),
        ),
        migrations.AlterField(
            model_name='modules',
            name='factor',
            field=models.PositiveIntegerField(default=0, verbose_name='Factor module'),
        ),
    ]
