# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20160802_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='naam_gebruiker',
            field=models.CharField(default='NAAM_GEBRUIKER', max_length=50),
        ),
    ]
