# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_modules_id_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='buy_module',
            field=models.PositiveIntegerField(default=0, verbose_name='Module kopen'),
        ),
    ]
