# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_modules_buy_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='exp_required',
            field=models.IntegerField(default=0, verbose_name='Experience benodigd'),
        ),
    ]
