# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_questions_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='naam_question_gebruiker',
            field=models.CharField(default='NAAM_QUESTION_GEBRUIKER', max_length=50),
        ),
    ]
