# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-16 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20160807_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='module_type',
            field=models.CharField(choices=[(b'Actief', b'Actief'), (b'Passief', b'Passief')], default=b'Passief', max_length=15),
        ),
    ]
